on:
  push:
    branches:
      - "gh-pages"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-storybook-to-github-pages@v1.0.2
      with:
        path: storybook-static
        install_command: npm i
        build_command: npm run build-storybook
